language: android
os: linux
dist: trusty
notifications:
  email: true
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-26
    # - sys-img-armeabi-v7a-android-17
before_script:
- chmod +x gradlew
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: SCt+p90wK7z0InEja8JoF24Uc+9MpVFqb+b6sE5gqOynDR0SDRHvmSAfdQ0r65We/UFI4GULHhSf1dg7laNG8OIs0d4LphE5yTbbBCRhEj9rWbpGuBeKXMQL5YVdC9wTu3zVTKmiscrFmTg0gtOG64wNH5VU8nZW0kPHC8+v7fglsmZMfFgA5ep8+XHBlCfWXmVcte49dnySm55Bznf7H9uoD0Db1ho7HHiQRno+uCbcmrZQ+m/x4mZF7vWrs2IlNs3ACIO3seBTL1Cg/GBdgynvQi9NldORQ1fkwI34i4QN3ZkUI30LXcxMs4LL7gIQVT3K3GKdoXREBSqGM7z/ZJYLQlHzm6bhOxE3ZKgjVfBpGggu/kBjg8h8wfnq/SYYUwai8943uy5dxjUTunW5j/c8uyTF1DPt7AxgM2Yy0Urr9ykHPOfNYjC+4F9W7h12S5/+otvRfVdtkmhy2oG+3BGFrw7+IefqLq5y2fB3jLRT31HNh+lX967mkAlHnI7noeuHftKUZ3p82GP0M1m2dVpEniWLNH26oSuNfh5mviI3+I+2Vzpt3O5o6bQPZQbw2Sn3+LmdWM8hq0SR+WhfnmjwXBbwEW32yVQJF6Z6T1LSwlS4RyVJdStqX0Isml3fVXu46taU9bCnFb6xr6Pm/Gg+oQYw0hIrePBIAShXZQM=
  file: app/build/outputs/apk/release/app-release.apk
  on:
    repo: a1203991686/PhotoXiu
    tags: true
  cleanup: 'false'
dd:
- openssl aes-256-cbc -K $encrypted_1d5650018551_key -iv $encrypted_1d5650018551_iv
  -in littlecorgi.jks.enc -out key/littlecorgi.jks -d
